#!/usr/bin/env python3
"""从 mem0 prompts.py 机械生成 Go prompt 常量 (逐字节搬运, diff=0 由构造保证)。

用法: python3 tools/gen_prompts.py /path/to/mem0/mem0/configs/prompts.py > core/prompts/prompts_gen.go
生成文件入库; prompt 文本变化时重跑。
"""
import json
import re
import sys


def main() -> None:
    src = sys.argv[1]
    namespace: dict = {}
    with open(src, "r", encoding="utf-8") as f:
        code = f.read()
    # 去掉依赖 import 后 exec (模块顶层仅 import + 常量 + 纯函数)
    exec(compile(code, src, "exec"), namespace)

    consts = {k: v for k, v in namespace.items() if re.fullmatch(r"[A-Z][A-Z0-9_]*", k) and isinstance(v, str)}
    funcs = {k: v for k, v in namespace.items() if callable(v) and not k.startswith("__")}

    out = []
    out.append("// Code generated by tools/gen_prompts.py from mem0/configs/prompts.py. DO NOT EDIT.")
    out.append("// prompt 文本逐字节搬运 (验收: prompts 与 Python 版 diff = 0, 由 core/prompts parity_test 校验)。")
    out.append("package prompts")
    out.append("")
    for name in sorted(consts):
        out.append(f"const {go_name(name)} = {go_expr(consts[name])}")
        out.append("")
    # 纯函数以 JSON 形式导出供 parity 校验, 行为在 prompts_manual.go 手工移植
    out.append("// parityManifest 供 parity_test 与 Python 版逐常量比对。")
    out.append("const parityManifestJSON = `" + json.dumps(sorted(consts.keys())) + "`")
    out.append("")
    print("\n".join(out))


def go_name(name: str) -> str:
    return name


def go_expr(text: str) -> str:
    """Go 常量表达式: raw string, 反引号用拼接转义 (保持常量表达式可 compile)。"""
    if "`" not in text:
        return "`" + text + "`"
    parts = text.split("`")
    exprs = []
    for i, part in enumerate(parts):
        if i > 0:
            exprs.append('"`"')
        if part:
            exprs.append("`" + part + "`")
    return " + ".join(exprs) if exprs else '""'



if __name__ == "__main__":
    main()
